### ISSUE TITLE
better documentation

### ISSUE THREAD

**Issue by jahpd** [greggman/html5bytebeat#3]
Some better documentation like wiki, or quick helps on main page about usage and functionality about some commands, like `DUP` and binary operators (some musicians can not understand the functionality)

**Comment by greggman** [comment]
Sorry, I didn't know musicians would be interested 😅

I just added some terse docs to the README.

Both otherwise it's just code. For **infix** see any JavaScript book. For **postfix** a forth book might help. 

Of course if you have ideas or you want to write more docs I'm happy to take pull requests.
