### ISSUE TITLE
Innacurate 't' value inside code

### ISSUE THREAD

**Issue by raphaelgoulart** [greggman/html5bytebeat#7]
First, I apologize in advance for not being able to name this properly, hopefully the examples make it clear.

Sometimes, when running the code, the t value is different than what it should be (what is shown in the interface). This can be seen [in this video](https://youtu.be/i7hsGbm4vaE).
(A brief explanation: `t/16 % 8` is just so I have an audio output that doesn't sound loud, and `tt=t` is just so I'm able to log t's value in the console. Most of the times that I do that - but not all - the value shown in the console is different than the one shown in the interface.

This affects codes that rely on 't' as an accurate timing source. This does NOT happen on saved .wav files, though, the issue only happens on browser playback.
An actual example:

- [How it's supposed to sound](https://instaud.io/3EgO), as exported from the 'save' button (I'm implemeting 2-op FM synthesis with ASDR support, and this is a test of that).
- [How it sounds in the browser](https://instaud.io/private/cfd3e3a6fe41406b47ff2ebfc675dceca214b766) (screen capture)
- [Source code](https://pastebin.com/c2Y14Gmu) (run at 22khz)

Thanks for reading!

**Comment by greggman** [comment]
That's strange. I don't know what the issue could be. If I add

```
,(sin(t * 0.05) * .5 + .5) * 255
```

to the bottom of your code `t` looks fine.

**Comment by raphaelgoulart** [comment]
Yeah, my guess is that `t` works correctly when used as audio output (the "actual t value" is used), but not so much when used as a timing source (the "wrong t value", seen in the browser console in my video, is used).

Using my song as an example - on the case of basic waveforms, that's not a huge issue since whether they're playing or muted is determined by `localTick >= note.start && localTick < note.end ? note.note : 0` (`localTick` being a value based on `t); `so if the `t` value is outside of that range for a brief moment, the note will just be muted for that brief moment, unnoticeable at best, and producing a click sound at worst.
However, FM is a bit more complex and uses ASDR; my implementation of release works that if the current time is outside of that range, it triggers the release state, thus fading out/stopping the note; so if the `t` value gets outside of that range, the note is halted, which sounds glitchy, as you probably noticed in the second audio.
Even if I remove the release part of it, attack and decay also rely on timers, and although the notes won't be randomly halted anymore, the instrument will still sound glitchy (I can make an example of that if you wish).
Reminder that, in both cases, the .wav output from the 'save' button sounds correct. It also sounds correct on [funute's bytebeat.js](https://pastebin.com/xwtRgcfV) (at least exporting to a .raw file, I wasn't able to test PulseAudio/ALSA audio output). So my guess is that the problem lies in the browser playback, somewhere.

**Comment by greggman** [comment]
It is strange. It's not a playback problem. if it was a playback problem then we would only hear the glitch but we see it too. The visualizer is just calling the same function to ask for values. 

If you feel like helping me fix it it would be really helpful if you could try to make your example smaller. Delete 99% of the table of notes and have the sequence repeat and see if it repos. Remove features and see if it repos. Compute only 2 channels and 1 channel and see if it repos.

That would be super helpful.

**Comment by greggman** [comment]
I think I know what the issue is. Just a guess. I have not dug through your code.

I'm guessing the issue is that your code is stateful? It's saving state from one call to the next. It expects that `t` goes 0, 1, 2, 3, 4 .... and so it saves off some values based on `t` and on the next call uses those values?

During playback though that's not what happens. The code is called multiple times with different values of `t`. One for playback, another for visualization. In both cases `t` is increasing like it's supposed to but they are increasing at different rates.

I'm not sure what solution I can offer. I could try to set some global variable `window.processingMode` or something or `window.contextId` for the various ways it's being called.

Another is maybe you could check something like

```
oldt = window.oldt || 0,
deltat = t - oldt,
window.oldt = t,
if (deltat !== 1) { must be a different context, or else the user reset the time }
```

I don't know that that is the issue but if there is anything stateful in the code then that would explain why playback is different than generating a wav.

**Comment by raphaelgoulart** [comment]
Yes, my code is stateful...mostly the FM part. I've reduced it to only 1 channel with an instrument that doesn't use attack, sustain fade and release fade; only decay, sustain and note off. [Here's the code](https://pastebin.com/KEGZchUB), and the [expected output](https://instaud.io/3FGf).

What happens during browser playback is notes stopping before they're supposed to.
Something that is weird (maybe helpful, maybe not), is that if one removes the release part of the code (commenting lines 78 to 81 and 110 to 117, and changing line 68 to `channel.freq = localTick >= note.start && localTick < note.end ? note.note : 0;`) it still glitches...during 3 loops. After the third loop (t ≈ 600k), it works normally.

**Comment by greggman** [comment]
I think maybe you missed my point.

This is how you think the code is called

```
let t = 0;
for(;;) {
   audio.addSample(byteBeatFunction(t++));
}
```

This is how it's actually called

```
let soundT = 0;
let visualizer1T = 0;
let visualizer2T = 0;

for (;;) {
   // do visualizer 1
   visualizer1.addSample(byteBeatFunction(visualizer1T++);

   // do visualizer 2
   visualizer2.addSample(byteBeatFunction(visualizer2T++));
   visualizer2.addSample(byteBeatFunction(visualizer2T++));  // yes, 2 samples for visualizer 2

   // do audio
   const t = soundT++;
   if (t % 1000 == 0) {   // no idea how often audio is asked for but it is chunked like this
      for(let i = 0; i < 1000; ++i) {
        audio.addSample(bytesBeatFunction(t + i);
      }
   }
}
```

So your function is being called with different values of `t` depending on if the code is calculating visualizer1, visualizer2, or the audio. When the exporter is running since there are no visualizers the problem goes away, there's only 1 `t` instead of 3 `t`s.

**Comment by raphaelgoulart** [comment]
Oh it is more clear now, thanks (it already was before, but I accidentally ignored it, sorry)
I also remembered that I can disable the visualizer on the player itself, and it works perfectly now (which solves my issue, but not the problem itself).

I'm fairly certain that the problem is that the code is processed from 0 to 999 for the audio, then it goes back to 1 for the visualizer, which throws off the timers in the code.

I can think of two possible solutions, idk how feasible it'd be to implement them, but here goes:
-Call the bytebeat code only once, store its result and use that as the argument for `addSample`
-Call the bytebeat code thrice, as you already do, but making it three different "instances" - as in, making sure the variables inside one instance of the code don't interact with the other. Maybe having byteBeatFunction1, 2 and 3, and making the variable inside of those local instead of global?

(I tested the "deltat thing" btw, it didn't change the outcome)

**Comment by raphaelgoulart** [comment]
Maybe a possible implementation of my first theoretical solution:
```
let t = 0;
let tArray = [] //pretend this has a fixed length of 1000

for (;;) {
    // do audio
    // also fills an array with 1000 elements, which is "re-filled" every 1000 t iterations
    if (t % 1000 == 0) {
        for(let i = 0; i < 1000; ++i) {
            var result = byteBeatFunction(t + i);
            audio.addSample(result);
            tArray[i] = result;
        }
    }

    // do visualizer 1
    visualizer1.addSample(tArray[t % 1000]); // uses already calculated result for a certain 't' value instead of going back and recalculating it

    // do visualizer 2
    visualizer2.addSample(tArray[t % 1000]);
    visualizer2.addSample(tArray[t % 1000]);  // yes, 2 samples for visualizer 2

    t++; //increases t for obvious reasons
}
}
```
This is untested, but it's probably good enough to give an idea. This way, the code will also only run once, which will probably be faster. If there's any mistake in this or a particular reason why this won't work, let me know!

**Comment by greggman** [comment]
Well so yea, I made 3 instances (thought of that the same time you did 🎉), but your small sample code has no state (vs the larger one) so that shouldn't matter.

For the life of me I can't figure out what the issue is.  I added this code to your smaller sample

```
oldTT = window.oldT || 0,
window.oldT = t,
window.not1Errors = t < 10 ? 0 : window.not1Errors || 0,
window.isZeroErrors = t < 10 ? 0 : window.isZeroErrors || 0,
window.largestDeltaT = t < 10 ? 0 : window.largestDeltaT || 0,
deltaT = t - oldTT,
t > 50000 && t < 100000
   ? window.largestDeltaT = max(window.largestDeltaT, deltaT) 
   : 0,
window.not1Errors += deltaT !== 1 ? 1 : 0,
window.isZeroErrors += deltaT === 0 ? 1 : 0,
```

And i see that sometimes the time increases by > 1. But checking with or without the visualizers the not1Errors increases exactly the same amount. largestDeltaT is 2 regardless of whether or not the visualizers are running.

Turning off the visualizers or just making the front tab not the front tab (since it's using requestAnimationFrame and requestAnimationFrame is not called when not the front tab) it of course works.

The code is now effectively this

```
const soundContext = new Context();
let soundT = 0;
const visualzer1Context = new Context();
let visualizer1T = 0;
const visualzer2Context = new Context();
let visualizer2T = 0;

for (;;) {
   // do visualizer 1
   visualizer1.addSample(byteBeatFunction(visualzer1Context, visualizer1T++);

   // do visualizer 2
   visualizer2.addSample(byteBeatFunction(visualzer2Context, visualizer2T++));
   visualizer2.addSample(byteBeatFunction(visualzer2Context, visualizer2T++));  // yes, 2 samples for visualizer 2

   // do audio
   const t = soundT++;
   if (t % 1000 == 0) {   // no idea how often audio is asked for but it is chunked like this
      for(let i = 0; i < 1000; ++i) {
        audio.addSample(soundContext, bytesBeatFunction(t + i));
      }
   }
}
```

and I can see that each context was getting the data you added in your original code and that each context is separate. I can also see in your short example nothing is added to the context. So, while that had to be a slight issue it wasn't the main issue.

I have no idea at the moment what the issue is.

I'll have to to think some more on it

**Comment by greggman** [comment]
Ok, I finally figured it out.

The issue is that every variable you're declaring is global to all of JavaScript

You put

```
SAMPLE_RATE = 11000,
...
```

Now open the JavaScript console and type `SAMPLE_RATE` and you'll see it

So, in your smaller sample the issue is `data` ends up being global which means all various calls to `byteBeatFunction` are using the same `data` and since `data.channels[..].ndx` ends up being shared across versions

The fix was change this

```
data = 
  (tick > 0 && typeof(data) !== "undefined") ?data : 
{
```

to

```
window.data = 
  (tick > 0 && typeof(window.data) !== "undefined") ? window.data : 
{
```

and then after that  change this

```
},

data.channels.forEach(function(channel) {
```

to this

```
},

data = window.data,
data.channels.forEach(function(channel) {
```

I'm not sure if there is anything I can do on my side to hide those variables from getting added to the global scope. If I use strict mode then everything breaks since declaring loose variables is disallowed.

I could add a version 2 mode or something where you supply the function so instead of

```
sin(t * 0.01)
```

You'd have to write 

```
// version: 2.0
function (t) {
  return sin(t * 0.0);
}
```

because then you could just write JavaScript but of course that's not really the point of byte beat. If you're just going to write JavaScript might as well not use bytebeat as a framework at all.

Anyway, you might have to clear your cache but if you make those changes it should now work with the latest version with the separate contexts. 

As for your original long example there were some bugs in the code where when it starts certain things are not defined once I fixed the scoping issues. If you fix those issues it should work too.

**Comment by greggman** [comment]
Actually I can maybe use an iframe. Checking....

**Comment by greggman** [comment]
Well I verified it would work but it's too big a change. As it is now the bytebeat code is compiled once but it would instead have to be compiled once for each context. It's not impossible but I don't really have the time to do it.

So for now, if you're saving state in a variable make sure it's something based off `window` as the `window` object is unique to each usage.

**Comment by raphaelgoulart** [comment]
Oh wow; the worst part is it actually _had_ `window.data` originally, but for some reason I removed it at some point (probably wanted to make variables name smaller or something). I should've googled the purpose of the 'window' variable before doing so, oops.

Also yeah, I'm also against the "v2" mode because it just wouldn't be bytebeat anymore.
And no need to make such a big change; adding "window." to stuff isn't hard at all, so I'll keep that in mind.
Thanks for the attention, and sorry for the inconvenience!
